# Generated by Django 3.0.6 on 2020-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transact', models.CharField(max_length=12)),
                ('input', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=150)),
            ],
        ),
    ]
